# Generated by Django 5.1.6 on 2026-09-22 08:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_group", "0010_quote_call_center_quote_gl_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="profit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
