# Generated by Django 5.1.6 on 2026-09-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_group", "0011_quote_profit_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="profit_amount",
        ),
    ]
