# Generated by Django 6.0.5 on 2026-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('project', 'Project'), ('task', 'Task'), ('quote', 'Quote'), ('login', 'User Login'), ('system', 'System Alert')], max_length=30),
        ),
    ]
