# Generated by Django 6.0.5 on 2026-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_entity_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='entity_id',
            new_name='record_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('project', 'Project'), ('task', 'Task'), ('contact', 'Contact'), ('login', 'User Login'), ('system', 'System Alert')], max_length=30),
        ),
    ]
