# Generated by Django 6.0.5 on 2026-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_entity_id_notification_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget'), ('expense', 'Expense'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('project', 'Project'), ('task', 'Task'), ('contact', 'Contact'), ('login', 'User Login'), ('system', 'System Alert'), ('TASK_ASSIGNED', 'Task Assigned')], max_length=30),
        ),
    ]
