# Generated by Django 5.1.6

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_poc_unique_together_remove_company_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[client.models.gstin_validator]),
        ),
    ]
