# Generated by Django 5.1.6 on 2026-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_currency'),
        ('product_group', '0008_quote_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='module',
        ),
        migrations.AddField(
            model_name='account',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='product_group.product_services'),
        ),
    ]
