# Generated by Django 6.0.5 on 2026-07-06 06:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_module_account_modules'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product_group', '0008_quote_currency'),
        ('roles', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='charges_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('charges_per_hour__gte', 0), ('charges_per_hour__isnull', True), _connector='OR'), name='account_charges_per_hour_non_negative'),
        ),
    ]
