# Generated by Django 5.1.6 on 2026-08-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_onboarding", "0002_add_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCodeSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="employeeonboardingrequest",
            name="employee_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
    ]
