# Generated by Django 5.1.6 on 2026-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0007_alter_quoteitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('SGD', 'Singapore Dollar (S$)'), ('JPY', 'Japanese Yen (¥)')], default='INR', max_length=3),
        ),
    ]
