# Generated by Django 5.1.6 on 2026-09-21 10:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancer_onboarding", "0015_grant_admin_archive_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelancerCodeSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="freelancer",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="freelancer_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="internal_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="permanent_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="profile_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="freelancer_profile_photo",
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_same_as_permanent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="temp_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="freelancerbankdetail",
            name="pan_verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="freelancerprojectassignment",
            name="allocation_percent",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="freelancerprojectassignment",
            name="planned_units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("invited", "Invited"),
                    ("onboarding", "Onboarding"),
                    ("completed", "Completed"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blocked", "Blocked"),
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("on_hold", "On Hold"),
                    ("offboarded", "Offboarded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FreelancerAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("rate_changed", "Pay Rate Changed"),
                            ("bank_detail_updated", "Bank Details Updated"),
                            ("pan_verification_changed", "PAN Verification Changed"),
                            ("status_changed", "Status Changed"),
                            ("project_assigned", "Project Assigned"),
                            ("project_removed", "Project Removed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freelancer_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreelancerEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("freelancer_owned", "Freelancer Owned"),
                            ("company_provided", "Company Provided"),
                            ("client_provided", "Client Provided"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("processor", models.CharField(blank=True, max_length=100)),
                ("ram", models.CharField(blank=True, max_length=50)),
                ("storage", models.CharField(blank=True, max_length=50)),
                ("operating_system", models.CharField(blank=True, max_length=100)),
                ("asset_id", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "freelancer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
            ],
        ),
    ]
