# Generated by Django 5.1.6 on 2026-08-19 09:22

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_onboarding", "0001_cleanup_legacy_state"),
        ("accounts", "0007_vendorreferencesequence_vendor_approved_at_and_more"),
        ("roles", "0002_add_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="accounts.vendor",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="vendor_onboarding.vendoraccesstoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorApprovalWorkflowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "company_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vendor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("freelancer", "Individual / Freelancer"),
                            ("company", "Company"),
                            ("partnership", "Partnership"),
                            ("proprietorship", "Proprietorship"),
                            ("llp", "LLP"),
                            ("government", "Government"),
                            ("non_profit", "Non-Profit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_configs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorApprovalInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level_order",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_action_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_instance",
                        to="accounts.vendor",
                    ),
                ),
                (
                    "resolved_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="vendor_onboarding.vendorapprovalworkflowconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=34)),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid IFSC code.",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                ("bank_id", models.CharField(blank=True, max_length=50)),
                ("bank_country_key", models.CharField(blank=True, max_length=10)),
                ("bank_control_key", models.CharField(blank=True, max_length=10)),
                ("branch", models.CharField(blank=True, max_length=150)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_detail",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("vendor_details", "Vendor Details"),
                            ("kyv_compliance", "KYV / Compliance"),
                            ("bank_details", "Bank Details"),
                            ("business_procurement", "Business / Procurement"),
                            ("documents", "Documents"),
                        ],
                        max_length=30,
                    ),
                ),
                ("required_changes", models.TextField()),
                ("comments", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_change_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_order",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("actor_role_snapshot", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("submitted", "Submitted"),
                            ("resubmitted", "Resubmitted"),
                            ("approved", "Approved"),
                            ("requested_changes", "Requested Changes"),
                        ],
                        max_length=25,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=25)),
                ("new_status", models.CharField(blank=True, max_length=25)),
                ("comments", models.TextField(blank=True)),
                ("required_changes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="accounts.vendor",
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="vendor_onboarding.vendorchangerequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendor approval history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="vendor_document"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pan", "PAN Document"),
                            ("gst_certificate", "GST Certificate"),
                            (
                                "cin_incorporation_certificate",
                                "CIN / Incorporation Certificate",
                            ),
                            ("msme_udyam_certificate", "UDYAM / MSME Certificate"),
                            ("epf_certificate", "EPF Certificate"),
                            ("esic_certificate", "ESIC Certificate"),
                            (
                                "bank_proof_cancelled_cheque",
                                "Bank Proof - Cancelled Cheque",
                            ),
                            (
                                "bank_proof_bank_statement",
                                "Bank Proof - Bank Statement",
                            ),
                            (
                                "bank_proof_bank_certificate",
                                "Bank Proof - Bank Certificate",
                            ),
                            ("other", "Other Document"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("uploaded", "Uploaded"), ("verified", "Verified")],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by_role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("vendor", "Vendor")],
                        default="vendor",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorKYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_of_tax_residence",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid PAN (format: AAAAA9999A).",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "cin",
                    models.CharField(
                        blank=True,
                        max_length=21,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid CIN.",
                                regex="^[LU][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$",
                            )
                        ],
                    ),
                ),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                (
                    "tan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid TAN.",
                                regex="^[A-Z]{4}[0-9]{5}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "tan_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number.",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                ("epf_number", models.CharField(blank=True, max_length=30)),
                ("esic_number", models.CharField(blank=True, max_length=30)),
                ("esic_district", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorOnboardingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(blank=True, max_length=50)),
                ("plant", models.CharField(blank=True, max_length=50)),
                ("contact_person_name", models.CharField(blank=True, max_length=150)),
                (
                    "contact_person_designation",
                    models.CharField(blank=True, max_length=100),
                ),
                ("gst_registered", models.BooleanField(default=False)),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid GSTIN (15 characters).",
                                regex="^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                ("msme_registered", models.BooleanField(default=False)),
                (
                    "udyam_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid UDYAM registration number.",
                                regex="^UDYAM-[A-Z]{2}-[0-9]{2}-[0-9]{7}$",
                            )
                        ],
                    ),
                ),
                (
                    "msme_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("micro", "Micro"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=20)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("vendor_introduction", models.TextField(blank=True)),
                ("finance_manager_name", models.CharField(blank=True, max_length=150)),
                (
                    "finance_manager_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("finance_manager_mobile", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_profile",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorProcurementDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_group", models.CharField(blank=True, max_length=100)),
                ("purchasing_org", models.CharField(blank=True, max_length=100)),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                ("order_currency", models.CharField(blank=True, max_length=3)),
                ("grouping_key", models.CharField(blank=True, max_length=100)),
                ("partner_category", models.CharField(blank=True, max_length=100)),
                ("incoterms_1", models.CharField(blank=True, max_length=100)),
                ("incoterms_2", models.CharField(blank=True, max_length=150)),
                (
                    "reconciliation_account",
                    models.CharField(blank=True, max_length=100),
                ),
                ("schema_group", models.CharField(blank=True, max_length=100)),
                ("gr_based_invoice_verification", models.BooleanField(default=False)),
                ("check_double_invoice", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_detail",
                        to="accounts.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_order", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                (
                    "approver_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_approval_levels",
                        to="roles.role",
                    ),
                ),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_approval_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="vendor_onboarding.vendorapprovalworkflowconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["level_order"],
                "unique_together": {("config", "level_order")},
            },
        ),
        migrations.CreateModel(
            name="VendorSubmissionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveSmallIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("is_resubmission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["version_number"],
                "unique_together": {("vendor", "version_number")},
            },
        ),
    ]
