# Generated by Django 5.1.6 on 2026-09-10 06:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Deliberately pinned to the migration that creates Project.Project
        # itself, NOT the latest Project migration - an uncommitted, unrelated
        # migration (0019, a different in-progress feature) was HEAD when this
        # was generated, and depending on it would force that unrelated
        # migration to ship as a prerequisite of this one.
        ("Project", "0001_initial"),
        ("freelancer_onboarding", "0003_grant_admin_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="available_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="hours_per_day",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="hours_per_week",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="notice_period_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="timezone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("invited", "Invited"),
                    ("onboarding", "Onboarding"),
                    ("completed", "Completed"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blocked", "Blocked"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FreelancerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("freelancer", "Freelancer"),
                            ("independent_contractor", "Independent Contractor"),
                            ("consultant", "Consultant"),
                            ("agency", "Agency"),
                        ],
                        default="freelancer",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                (
                    "notice_period_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("nda_signed", models.BooleanField(default=False)),
                ("agreement_signed", models.BooleanField(default=False)),
                (
                    "document",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="freelancer_contract",
                    ),
                ),
                ("document_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freelancer_contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="FreelancerRateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("fixed", "Fixed Price"),
                            ("milestone", "Milestone"),
                            ("retainer", "Retainer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("billing_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee (₹)"),
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("SGD", "Singapore Dollar (S$)"),
                            ("JPY", "Japanese Yen (¥)"),
                        ],
                        default="INR",
                        max_length=10,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "minimum_billable_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "weekend_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freelancer_rate_cards_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_cards",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="FreelancerProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "allocated_hours",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("pricing_model_snapshot", models.CharField(blank=True, max_length=20)),
                (
                    "cost_rate_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "billing_rate_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency_snapshot", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freelancer_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_assignments",
                        to="Project.project",
                    ),
                ),
                (
                    "rate_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="freelancer_onboarding.freelancerratecard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
