# Generated by Django 6.0.5 on 2026-07-06 06:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_remove_projectbudget_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='bills_and_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='task',
            name='allocated_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='taskextrahoursrequest',
            name='approved_allocated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='taskextrahoursrequest',
            name='previous_allocated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='taskextrahoursrequest',
            name='requested_hours',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'title')},
        ),
        migrations.AddConstraint(
            model_name='projectbudget',
            constraint=models.CheckConstraint(condition=models.Q(('total_budget__gte', 0), ('total_budget__isnull', True), _connector='OR'), name='projectbudget_total_budget_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='projectbudget',
            constraint=models.CheckConstraint(condition=models.Q(('bills_and_expenses__gte', 0), ('bills_and_expenses__isnull', True), _connector='OR'), name='projectbudget_bills_and_expenses_non_negative'),
        ),
    ]
