# Generated by Django 5.1.6 on 2026-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0018_remove_projectbudget_tax_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="poc_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the POC in accounts.Account (employee) or accounts.Vendor (vendor/freelancer), per poc_type.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="poc_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employee", "Employee"),
                    ("vendor", "Vendor"),
                    ("freelancer", "Freelancer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
