# Generated by Django 5.1.6 on 2026-09-17 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0022_project_billing_frequency_project_contract_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contract Value x Project %, or entered directly.",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of the Contract Value carved out for this project.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contract Value minus Project Amount. Always auto-calculated, never entered directly.",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
