# Generated by Django 5.1.6 on 2026-09-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freelancer_onboarding",
            "0009_grant_admin_task_assignment_time_entry_permissions",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("pan", "PAN Document"),
                    ("other", "Other Document"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FreelancerBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("paypal", "PayPal"),
                            ("wise", "Wise"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=34)),
                ("ifsc_code", models.CharField(blank=True, max_length=11)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "freelancer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_detail",
                        to="freelancer_onboarding.freelancer",
                    ),
                ),
            ],
        ),
    ]
