# Generated by Django 5.1.6 on 2026-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancer_onboarding", "0012_grant_admin_bank_detail_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
