# Generated by Django 5.1.6 on 2026-02-11 12:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_company_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter mobile number with country code (e.g. +919876543210)', max_length=128, region=None, unique=True),
        ),
    ]
