# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_poc_poc_mobile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poc',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='company',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_address',
        ),
        migrations.AddField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='poc',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poc',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poc',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poc',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='poc',
            name='poc_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='poc',
            unique_together={('company', 'first_name', 'last_name', 'poc_mobile', 'poc_email')},
        ),
    ]
