# Generated by Django 5.1.6 on 2026-09-23 09:29

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_company_gstin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="authorised_signatory_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="authorised_signatory_role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_code",
            field=models.CharField(
                blank=True, help_text="IFSC / SWIFT / IBAN", max_length=34
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("company", "Company"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                default="company",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "Indian Rupee (₹)"),
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("SGD", "Singapore Dollar (S$)"),
                    ("JPY", "Japanese Yen (¥)"),
                ],
                default="INR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("verified", "Verified"),
                    ("enhanced_review", "Enhanced Review"),
                    ("review_due", "Review Due"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("intake", "Intake"),
                    ("identity_kyc", "Identity & KYC"),
                    ("compliance", "Compliance"),
                    ("banking", "Banking"),
                    ("commercials", "Commercials"),
                    ("approved", "Approved"),
                ],
                default="intake",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="pan",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid PAN (10 characters, e.g. AAAAA9999A).",
                        regex="^[A-Z]{5}\\d{4}[A-Z]{1}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_no",
            field=models.CharField(
                blank=True,
                help_text="CIN / LLPIN / company registration number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="risk_rating",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ClientAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Client Created"),
                            ("updated", "Client Updated"),
                            ("kyc_status_changed", "KYC Status Changed"),
                            ("risk_rating_changed", "Risk Rating Changed"),
                            ("document_uploaded", "Document Uploaded"),
                            ("deleted", "Client Deleted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="client.company",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="client_document"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("registration_certificate", "Registration Certificate"),
                            ("tax_certificate", "Tax Certificate"),
                            ("bank_proof", "Bank Proof"),
                            ("authorised_signatory_id", "Authorised Signatory ID"),
                            ("sanctions_screening", "Sanctions Screening"),
                            ("other", "Other Document"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("uploaded", "Uploaded"), ("verified", "Verified")],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="client.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
