# Generated by Django 5.1.6 on 2026-09-23 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_grant_admin_client_kyc_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdocument",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_documents_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="approval_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="banking_verification_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not Verified"),
                    ("documents_uploaded", "Documents Uploaded"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="beneficial_ownership_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not Verified"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="billing_contact",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="billing_frequency",
            field=models.CharField(
                choices=[
                    ("one_time", "One Time"),
                    ("monthly", "Monthly"),
                    ("milestone_based", "Milestone Based"),
                    ("custom", "Custom"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="commercial_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="compliance_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="compliance_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="compliance_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_compliance_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="custom_payment_terms",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="company",
            name="enhanced_due_diligence_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("required", "Required"),
                    ("completed", "Completed"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_requirements",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Invoice"),
                    ("po_required", "Client PO Required"),
                    ("other", "Other"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="kyc_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="kyc_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_kyc_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("due_on_receipt", "Due on Receipt"),
                    ("net_15", "Net 15"),
                    ("net_30", "Net 30"),
                    ("net_45", "Net 45"),
                    ("net_60", "Net 60"),
                    ("net_90", "Net 90"),
                    ("custom", "Custom"),
                ],
                default="net_30",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="po_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="sanctions_screening_status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not Checked"),
                    ("in_progress", "In Progress"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="not_checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Overseas equivalent of GSTIN/PAN - VAT / EIN / Tax ID. No fixed format (varies by country).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tax_residency_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("requires_review", "Requires Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="withholding_tax_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="withholding_tax_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="clientauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Client Created"),
                    ("updated", "Client Updated"),
                    ("kyc_status_changed", "KYC Status Changed"),
                    ("risk_rating_changed", "Risk Rating Changed"),
                    ("document_uploaded", "Document Uploaded"),
                    ("deleted", "Client Deleted"),
                    ("compliance_updated", "Compliance Updated"),
                    ("banking_verified", "Banking Verified"),
                    ("banking_rejected", "Banking Rejected"),
                    ("commercials_completed", "Commercials Completed"),
                    ("kyc_submitted", "KYC Submitted for Approval"),
                    ("change_requested", "Changes Requested"),
                    ("change_resolved", "Change Request Resolved"),
                    ("project_ready_marked", "Marked Project Ready"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("registration_certificate", "Registration Certificate"),
                    ("tax_certificate", "Tax Certificate"),
                    ("bank_proof", "Bank Proof"),
                    ("authorised_signatory_id", "Authorised Signatory ID"),
                    ("sanctions_screening", "Sanctions Screening"),
                    ("gst_certificate", "GST Certificate"),
                    ("pan_document", "PAN Document"),
                    ("cin_llpin", "CIN / LLPIN"),
                    ("w8ben_e", "W-8BEN-E"),
                    ("beneficial_ownership_proof", "Beneficial Ownership Document"),
                    ("other", "Other Document"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("identity_kyc", "Identity & KYC"),
                            ("compliance", "Compliance"),
                            ("banking", "Banking"),
                            ("commercials", "Commercials"),
                            ("documents", "Documents"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required_changes", models.TextField()),
                ("comments", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="client.company",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_change_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
