# Generated by Django 5.1.6 on 2026-09-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_grant_admin_manager_client_deep_workflow_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("registration_certificate", "Registration Certificate"),
                    ("tax_certificate", "Tax Certificate"),
                    ("bank_proof", "Bank Proof"),
                    ("authorised_signatory_id", "Authorised Signatory ID"),
                    ("sanctions_screening", "Sanctions Screening"),
                    ("gst_certificate", "GST Certificate"),
                    ("pan_document", "PAN Document"),
                    ("cin_llpin", "CIN / LLPIN"),
                    ("w8ben_e", "W-8BEN-E"),
                    ("beneficial_ownership_proof", "Beneficial Ownership Document"),
                    ("tax_residency_certificate", "Tax Residency Document"),
                    ("other", "Other Document"),
                ],
                max_length=40,
            ),
        ),
    ]
