# Generated by Django 5.1.6 on 2026-08-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_account_module_account_modules"),
        ("vendor_onboarding", "0001_cleanup_legacy_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorReferenceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="vendor",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="company_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_person_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendors_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="initial_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="internal_requester",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendor",
            name="last_saved_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vendor",
            name="plant",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("action_required", "Action Required"),
                    ("resubmitted", "Resubmitted"),
                    ("approval_in_progress", "Approval In Progress"),
                    ("approved", "Approved"),
                ],
                db_index=True,
                default="approved",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="submitted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_reference_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("freelancer", "Individual / Freelancer"),
                    ("company", "Company"),
                    ("partnership", "Partnership"),
                    ("proprietorship", "Proprietorship"),
                    ("llp", "LLP"),
                    ("government", "Government"),
                    ("non_profit", "Non-Profit"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
