# Generated by Django 5.1.6 on 2026-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_vendorreferencesequence_vendor_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
