# Generated by Django 5.1.6 on 2026-09-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0010_alter_expense_created_by_alter_expense_expense_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="core.glaccount",
            ),
        ),
    ]
