# Generated by Django 5.1.6 on 2026-10-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0024_task_milestone"),
        ("core", "0002_notification"),
        ("finances", "0018_vendorbill_standalone_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="vendor_bill",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_expense",
                to="finances.vendorbill",
            ),
        ),
        migrations.AddField(
            model_name="vendorbill",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_bills",
                to="core.glaccount",
            ),
        ),
        migrations.AddField(
            model_name="vendorbill",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_bills",
                to="Project.milestone",
            ),
        ),
    ]
