# Generated by Django 5.1.6 on 2026-10-09 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0028_tm_monthly_periods"),
        ("client", "0007_company_gstin"),
        ("finances", "0019_expense_vendor_bill_vendorbill_gl_account_and_more"),
        ("product_group", "0012_remove_quote_profit_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="Project.projectperiod",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Cancelled"), _negated=True),
                fields=("billing_period",),
                name="one_open_invoice_per_billing_period",
            ),
        ),
    ]
