# Generated by Django 5.1.6 on 2026-09-28 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_vendor_is_archived"),
        ("vendor_onboarding", "0005_grant_admin_vendor_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorbankdetail",
            name="bank_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendorbankdetail",
            name="bank_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorbankdetail",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="vendorbankdetail",
            name="swift_code",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="vendorbankdetail",
            name="verification_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorbankdetail",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not Verified"),
                    ("documents_uploaded", "Documents Uploaded"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendordocument",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendordocument",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendordocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_documents_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendorkyc",
            name="beneficial_ownership_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorkyc",
            name="compliance_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorkyc",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("enhanced_review", "Enhanced Review"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorkyc",
            name="risk_rating",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vendorkyc",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingprofile",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendoronboardingprofile",
            name="service_category",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="billing_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one_time", "One Time"),
                    ("monthly", "Monthly"),
                    ("milestone_based", "Milestone Based"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="contract_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="custom_payment_terms",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="po_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="rate_unit",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="service_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="tax_remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="withholding_tax_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprocurementdetail",
            name="withholding_tax_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendordocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("pan", "PAN Document"),
                    ("gst_certificate", "GST Certificate"),
                    (
                        "cin_incorporation_certificate",
                        "CIN / Incorporation Certificate",
                    ),
                    ("msme_udyam_certificate", "UDYAM / MSME Certificate"),
                    ("epf_certificate", "EPF Certificate"),
                    ("esic_certificate", "ESIC Certificate"),
                    ("bank_proof_cancelled_cheque", "Bank Proof - Cancelled Cheque"),
                    ("bank_proof_bank_statement", "Bank Proof - Bank Statement"),
                    ("bank_proof_bank_certificate", "Bank Proof - Bank Certificate"),
                    ("authorised_signatory_proof", "Authorised Signatory Proof"),
                    ("beneficial_ownership_proof", "Beneficial Ownership Document"),
                    ("registration_certificate", "Company Registration Document"),
                    ("tax_id_certificate", "VAT / EIN / Tax ID Certificate"),
                    ("tax_residency_certificate", "Tax Residency Document"),
                    ("tax_form", "W-8BEN-E / Applicable Tax Form"),
                    ("contract_document", "Contract Document"),
                    ("other", "Other Document"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="vendordocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VendorAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Vendor Created"),
                            ("onboarding_started", "Onboarding Started"),
                            ("updated", "Vendor Edited"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_verified", "Document Verified"),
                            ("document_rejected", "Document Rejected"),
                            ("document_deleted", "Document Deleted"),
                            ("kyc_updated", "KYC Updated"),
                            ("banking_verified", "Banking Verified"),
                            ("banking_updated", "Banking Review Updated"),
                            ("contract_updated", "Contract Updated"),
                            ("email_sent", "Onboarding Email Sent"),
                            ("email_failed", "Onboarding Email Failed"),
                            ("submitted", "Vendor Submitted"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Vendor Approved"),
                            ("rejected", "Vendor Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                ("performed_by_label", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=255)),
                ("sender", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
