# Generated by Django 5.1.6 on 2026-09-15 12:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0021_budgetline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="billing_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total agreed contract value for a Fixed Budget project.",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="engagement_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Budget / Milestone-Based"),
                    ("time_and_material", "Time & Material (T&M)"),
                ],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="monthly_billing_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Recurring client billing amount per billing period (T&M).",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                help_text="e.g. Net 30, Net 15, Due on Receipt.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                (
                    "completion_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="Project.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("freelancer", "Freelancer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        help_text="ID in accounts.Account (employee) or accounts.Vendor (freelancer), per resource_type."
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cost_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly cost rate.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billing_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate billed to the client.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "allocation_percent",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Hours for one billing period, used to derive Monthly Cost/Billing.",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="Project.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_assignments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "id"],
            },
        ),
    ]
