# Generated by Django 5.1.6 on 2026-10-08 10:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0024_task_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceassignment",
            name="cost_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="resourceassignment",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_assignments",
                to="Project.milestone",
            ),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="billing_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Hourly rate billed to the client.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="cost_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Hourly cost rate.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="resource_id",
            field=models.PositiveIntegerField(
                help_text="ID in accounts.Account (employee), freelancer_onboarding.Freelancer (freelancer) or accounts.Vendor (vendor), per resource_type."
            ),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("freelancer", "Freelancer"),
                    ("vendor", "Vendor / External"),
                ],
                max_length=20,
            ),
        ),
    ]
