# Generated by Django 5.1.6 on 2026-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0025_resourceassignment_cost_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceassignment",
            name="external_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="resource_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID in accounts.Account (employee), freelancer_onboarding.Freelancer (freelancer) or accounts.Vendor (vendor), per resource_type. Empty for an external resource.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceassignment",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("freelancer", "Freelancer"),
                    ("vendor", "Vendor"),
                    ("external", "External Resource"),
                ],
                max_length=20,
            ),
        ),
    ]
