# Generated by Django 5.1.6 on 2026-10-09 19:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0027_widen_task_allocated_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly cost budget (T&M). Defaults to the monthly billing amount.",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="ProjectPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("amounts_overridden", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "month"), name="unique_project_period_month"
                    )
                ],
            },
        ),
    ]
