# Generated by Django 5.1.6 on 2026-08-21 07:00

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("personal_details", "Personal Details"),
                            ("address", "Address"),
                            ("statutory_details", "Statutory Details"),
                            ("bank_details", "Bank Details"),
                            ("emergency_contact", "Emergency Contact"),
                            ("documents", "Documents"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField()),
                ("comments", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_change_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeOnboardingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=30, unique=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                        ],
                        max_length=20,
                    ),
                ),
                ("work_location", models.CharField(blank=True, max_length=150)),
                ("pf_applicable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("action_required", "Action Required"),
                            ("resubmitted", "Resubmitted"),
                            ("approved", "Approved"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("last_saved_step", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_onboarding_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeOnboardingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role_snapshot", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("submitted", "Submitted"),
                            ("resubmitted", "Resubmitted"),
                            ("approved", "Approved"),
                            ("requested_changes", "Requested Changes"),
                        ],
                        max_length=25,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=25)),
                ("new_status", models.CharField(blank=True, max_length=25)),
                ("comments", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_onboarding_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="employee_onboarding.employeechangerequest",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee onboarding history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number.",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="employee_document"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pan", "PAN Card"),
                            ("aadhaar", "Aadhaar Card"),
                            ("bank_proof", "Bank Proof / Cancelled Cheque"),
                            ("photo", "Passport-size Photo"),
                            ("education_certificate", "Highest Education Certificate"),
                            ("experience_certificate", "Experience Certificate"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("esic", "ESIC Document"),
                            ("other", "Other Document"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("uploaded", "Uploaded"), ("verified", "Verified")],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by_role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("employee", "Employee")],
                        default="employee",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employeechangerequest",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="employee_onboarding.employeeonboardingrequest",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=34)),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid IFSC code.",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_detail",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAddressDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_detail",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="employee_onboarding.employeeaccesstoken",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePersonalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number.",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number.",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("marital_status", models.CharField(blank=True, max_length=20)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_detail",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeStatutoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid PAN (format: AAAAA9999A).",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]$",
                            )
                        ],
                    ),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 12-digit Aadhaar number.",
                                regex="^[0-9]{12}$",
                            )
                        ],
                    ),
                ),
                (
                    "uan_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 12-digit UAN.",
                                regex="^[0-9]{12}$",
                            )
                        ],
                    ),
                ),
                ("tan", models.CharField(blank=True, max_length=10)),
                ("esic_number", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statutory_detail",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSubmissionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveSmallIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("is_resubmission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="employee_onboarding.employeeonboardingrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["version_number"],
                "unique_together": {("request", "version_number")},
            },
        ),
    ]
