"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load .env before anything below reads an environment variable - this must
# come first, or SECRET_KEY/DEBUG/etc. below would read the process
# environment before .env's values ever reached it.
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Set a real
# value in .env (SECRET_KEY=...) - never hard-code one here, this file is
# committed to a public repo.
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-CHANGE-ME-for-local-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"
# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     # "t847rjkh-3000.inc1.devtunnels.ms",
#     # 't847rjkh-5173.inc1.devtunnels.ms'
# ]
ALLOWED_HOSTS = ["*"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000",
    "https://project.nxsys.in",
    # "https://t847rjkh-3000.inc1.devtunnels.ms",
    # "https://t847rjkh-5173.inc1.devtunnels.ms/",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000",
    "https://project.nxsys.in",
    # "https://t847rjkh-3000.inc1.devtunnels.ms",
    # "https://t847rjkh-5173.inc1.devtunnels.ms/",
]

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'rest_framework_simplejwt',
    'corsheaders',
    # 'module',
    'product_group',
    'roles',
    'client',
    'Project',
    "channels",
    'finances',
    'Reports',
    'core',
    'phonenumber_field',
    'vendor_onboarding',
    'employee_onboarding',


]
ASGI_APPLICATION = "myproject.asgi.application"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        # RedisChannelLayer (channels_redis.core) requires Redis >= 5.0 (BZPOPMIN).
        # The local Redis server is the old 3.0.504 Windows build, so we use the
        # Pub/Sub-based layer instead, which only needs SUBSCRIBE/PUBLISH and
        # works on any Redis version. This app only uses group_add/group_discard/
        # group_send (no point-to-point channel_layer.send), which PubSub fully supports.
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 30,
        }
    }
}

CONN_MAX_AGE = 0

# import dj_database_url
# import os

# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.getenv("DATABASE_URL"),
#         conn_max_age=600,
#         ssl_require=True,
#     )
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "myproject.exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        # Public, token-authenticated vendor/employee onboarding endpoints -
        # no login, so they're rate-limited per IP instead of per user.
        "vendor_public": "60/hour",
        # A single employee onboarding session legitimately fires 40-60+
        # requests before reaching the documents step (choices + detail on
        # load, an identity/last_saved_step PATCH per step advance, a section
        # PATCH per step, a documents-list refetch after every upload/delete,
        # etc.), so 60/hour was exhausted mid-session and caused genuine
        # users to be 429'd (e.g. after PAN/Aadhaar upload, by the time Bank
        # Proof/Photo were reached the bucket was already empty). Rate-limit
        # per-minute instead of per-hour so a legitimate burst has headroom
        # and an accidental trip recovers in seconds, not up to an hour.
        "employee_onboarding_public": "300/min",
    },
}

# Vendor Self-Service Onboarding
VENDOR_ONBOARDING_TOKEN_TTL_DAYS = 90

# Employee Self-Service Onboarding
EMPLOYEE_ONBOARDING_TOKEN_TTL_DAYS = 30




SESSION_COOKIE_AGE = 60 * 60 * 24   # 1 day
SESSION_COOKIE_SECURE = False       # True in production (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = False          # True in production
CSRF_COOKIE_SAMESITE = "Lax"


    

# DEFAULT_FROM_EMAIL = "Your App <no-reply@yourdomain.com>"


# Email settings for development (prints emails to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


PASSWORD_RESET_OTP_EXPIRY_MINUTES = 2
AUTH_USER_MODEL = 'accounts.Account'


from datetime import timedelta 

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    
    # Clock skew tolerance (allows up to 60 seconds difference between client/server time)
    'LEEWAY': timedelta(seconds=60),
    
    # Algorithm
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    # Token type
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

FRONTEND_BASE_URL = "http://localhost:5173"

# Public URL the Vendor Onboarding portal is reachable at - used only to build
# the secure onboarding link sent in the invite/request-changes emails. Never
# hard-code localhost here: a vendor opening the email is on their own
# computer/network, not the dev machine. Set this in .env:
#   local:      VENDOR_PORTAL_URL=http://localhost:5173
#   tunnel:     VENDOR_PORTAL_URL=https://xxxx.ngrok-free.app
#   production: VENDOR_PORTAL_URL=https://vendor.yourcompany.com
# Falls back to FRONTEND_BASE_URL (shared with other features' email links)
# if not set, so this is a no-op change until VENDOR_PORTAL_URL is configured.
VENDOR_PORTAL_URL = os.environ.get("VENDOR_PORTAL_URL", FRONTEND_BASE_URL).rstrip("/")

# So a tunneled/production vendor-portal origin can call the public
# vendor-onboarding API directly (see CORS_ALLOWED_ORIGINS above) without
# needing that origin hand-added every time VENDOR_PORTAL_URL changes.
if VENDOR_PORTAL_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(VENDOR_PORTAL_URL)

# Public URL the Employee Onboarding portal is reachable at - same idea as
# VENDOR_PORTAL_URL above, kept as its own env var so the two portals can be
# pointed at different deployments later even though they currently share the
# same frontend app. Set this in .env, e.g.:
#   production: EMPLOYEE_PORTAL_URL=https://project.nxsys.in
EMPLOYEE_PORTAL_URL = os.environ.get("EMPLOYEE_PORTAL_URL", FRONTEND_BASE_URL).rstrip("/")

if EMPLOYEE_PORTAL_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(EMPLOYEE_PORTAL_URL)

# Branding used in Vendor Onboarding emails. COMPANY_LOGO_URL must be a full
# https:// URL to a hosted image (email clients can't load relative/local
# paths) - leave it blank to fall back to a text-only header, which is the
# same convention this codebase's other email templates already use.
COMPANY_NAME = os.environ.get("COMPANY_NAME", "SRIA INFOTECH PRIVATE LTD")
COMPANY_LOGO_URL = os.environ.get("COMPANY_LOGO_URL", "")
COMPANY_WEBSITE = os.environ.get("COMPANY_WEBSITE", "www.sriainfotech.com")
# Shown in the account-created email footer when set - blank hides the line,
# same convention as COMPANY_LOGO_URL above.
COMPANY_EMAIL = os.environ.get("COMPANY_EMAIL", "")
COMPANY_PHONE = os.environ.get("COMPANY_PHONE", "")
# print("Cloud Name:", os.environ.get("CLOUDINARY_CLOUD_NAME"))
# print("APiKey", os.environ.get("CLOUDINARY_API_KEY"))
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get("CLOUDINARY_CLOUD_NAME"),
    'API_KEY':os.environ.get("CLOUDINARY_API_KEY"),
    'API_SECRET':os.environ.get("CLOUDINARY_API_SECRET"),
    'SECURE': True,
    'AUTHENTICATED': False,
}
 
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
 
# ✅ Cloudinary media configuration
MEDIA_ROOT = BASE_DIR / 'media'  # Fallback/temp path

 
# Don't set MEDIA_URL - let cloudinary_storage generate the correct URL automatically
# The package will create URLs like: https://res.cloudinary.com/{cloud_name}/image/upload/{path}
 
# print("Using Cloudinary for media storage in production.")


# STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Set these in .env - never hard-code a real mailbox/App Password here, this
# file is committed to a public repo.
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = "teerdavenigedela@gmail.com"



CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Run tasks (emails, etc.) synchronously in-process instead of via a
# separate Celery worker consuming Redis. Tied to DEBUG rather than a
# standalone flag: if a worker silently isn't running (easy to miss - it's
# a separate process from `runserver`), queued emails just sit unsent with
# no visible error. Eager mode makes that failure mode impossible in dev at
# the cost of blocking ~4-5s (real SMTP send time) on any action that sends
# mail. EAGER_PROPAGATES=True so a failing task raises here instead of
# silently vanishing, since there's no worker log to check anymore.
CELERY_TASK_ALWAYS_EAGER = DEBUG
CELERY_TASK_EAGER_PROPAGATES = DEBUG

APPEND_SLASH=False 
PHONENUMBER_DEFAULT_REGION = "IN"
