# Generated by Django 5.1.6 on 2026-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0006_quoteitem_is_outsourced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes'), ('months', 'Months')], default='pieces', max_length=10),
        ),
    ]
