# Generated by Django 5.1.6 on 2026-09-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0018_remove_projectbudget_tax_amount_and_more"),
        ("product_group", "0008_quote_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="linked_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_quotes",
                to="Project.project",
            ),
        ),
    ]
