# Generated by Django 6.0.5 on 2026-07-06 06:37

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_poc_poc_mobile'),
        ('product_group', '0008_quote_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='in_house_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='invoiced_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='outsourced_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='to_be_invoiced_sum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('quote', 'product_service')},
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('sub_total__gte', 0)), name='quote_sub_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='quote_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='quote_total_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_unit__gte', 0)), name='quoteitem_price_per_unit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='quoteitem_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='quoteitem_amount_non_negative'),
        ),
    ]
