# Generated by Django 6.0.5 on 2026-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0009_alter_quote_in_house_cost_alter_quote_invoiced_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_services',
            name='technologies',
            field=models.TextField(blank=True, help_text='Comma-separated list of technologies', null=True),
        ),
    ]
