# Generated by Django 5.1.6 on 2026-09-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0022_project_billing_frequency_project_contract_value_and_more"),
        ("finances", "0011_expense_gl_account"),
        ("product_group", "0010_quote_call_center_quote_gl_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="Project.milestone",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="Project.milestone",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="product_group.quote",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product_group.product_services",
            ),
        ),
    ]
