# Generated by Django 5.1.6 on 2026-09-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0012_expense_milestone_invoice_billing_period_end_and_more"),
        ("freelancer_onboarding", "0018_grant_admin_equipment_and_pan_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="freelancer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="freelancer_onboarding.freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("travel", "Travel"),
                    ("food", "Food"),
                    ("internet", "Internet"),
                    ("electricity", "Electricity"),
                    ("software", "Software"),
                    ("maintenance", "Maintenance"),
                    ("freelancer", "Freelancer Cost"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
