# Generated by Django 5.1.6 on 2026-09-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HrmsEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("designation", models.CharField(blank=True, max_length=150)),
                ("hrms_role", models.CharField(blank=True, max_length=150)),
                ("branch", models.CharField(blank=True, max_length=150)),
                ("is_active_in_hrms", models.BooleanField(db_index=True, default=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("removed_from_hrms_at", models.DateTimeField(blank=True, null=True)),
                ("is_eligible", models.BooleanField(db_index=True, default=False)),
                ("access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("access_revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hrms_missing", "Missing from HRMS sync"),
                            ("manual", "Revoked manually"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hrms_access_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hrms_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "employee_id"],
            },
        ),
        migrations.CreateModel(
            name="HrmsSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("returned_count", models.PositiveIntegerField(default=0)),
                ("removed_count", models.PositiveIntegerField(default=0)),
                ("access_revoked_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hrms_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
